name: test
channels:
  - conda-forge
dependencies:
  - python=3.9
  - mock
  - pytest-qt
  - pytest==6.1.1
  - pytest-cov
  - pytest-mock
  - coverage
  - check-manifest
#   - pre-commit
  - tqdm
  - twine
