name: CD

on:
  release:
    types: [created]

jobs:
  make-release:
    runs-on: windows-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest" 
          python-version: "3.8"
          channel-priority: "strict"
          channels: "conda-forge"  
          mamba-version: "*"
          show-channel-urls: true 

      - name: Setup build dependencies
        run: mamba install -n test --file requirements/build.txt -c conda-forge -y -q

      - name: Tag to version
        shell: bash -l {0}
        run: |
          echo "__version__='${GITHUB_REF#refs/*/}'" >> spyder_screencast/__init__.py
          echo "__version__='${GITHUB_REF#refs/*/}'"

      - name: Create package
        shell: bash -l {0}
        run: python setup.py sdist 

      - name: Check package
        shell: bash -l {0}
        run: twine check dist/*

      - name: Check manifest
        shell: bash -l {0}
        run: check-manifest

      - name: Upload to PyPI
        shell: bash -l {0}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: python -m twine upload dist/*

