name: CI

on: [push]

jobs:
  test-windows:
    runs-on: windows-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      - name: provision-with-micromamba
        uses: mamba-org/provision-with-micromamba@v10
        with:
          environment-file: requirements/build.yml

      - name: Create package
        shell: bash -l {0}
        run: python setup.py sdist 

      - name: Check package
        shell: bash -l {0}
        run: twine check dist/*

      - name: Check manifest
        shell: bash -l {0}
        run: check-manifest
