name: CI

on: [push]

jobs:
  test-windows:
    runs-on: windows-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest" 
          python-version: "3.8"
          channel-priority: "strict"
          channels: "conda-forge"  
          mamba-version: "*"
          show-channel-urls: true 

      - name: Setup project dependencies
        run: |
          mamba install -n test --file requirements/build.txt -c conda-forge -y -q

      - name: Create package
        shell: bash -l {0}
        run: python setup.py sdist 

      - name: Check package
        shell: bash -l {0}
        run: twine check dist/*

      - name: Check manifest
        shell: bash -l {0}
        run: check-manifest
